RabbitMQ Events [User Stories 12, 17, 18, 22]
SmartCityProjectGroup/SC_Microservice9 pull request #3
Opened 2022-04-30 16:21 UTC by jt128

Add all RabbitMQ Events to API.
- json-Schema for every Event
- json-Schema for every POST API call
- test cases for end-to-end and correct attributes

Completes User Story 17, 18 ,22  and parts of User Story 1, 12, 21 for MVP.

2022-04-30 16:27 UTC, jt128 commented
muss erst noch ein Github Secret für RabbitMQ gesetzt werden, sonst scheitern die Test.

2022-05-02 08:14 UTC, SgtEpic requested changes
Wenn ich das richtig verstehe, dann sollen die Events über eigene API Calls ausgelöst werden, sodass das Frontend für diese Anfragen zwei Requests stellen müsste? 

Wenn ja, dann geht das so natürlich nicht. Das Frontend darf von den Events im Hintergrund nichts mitbekommen. Das Schicken der Events und das Bearbeiten mit den Datenbankanfragen, muss durch einen API Call ausgelöst werden.

---

Dann haben wir wieder das Thema Spezifikation: Da geht jetzt nicht hervor, welche Daten und in welcher Form man die jetzt an deinen Server schicken soll. 

Für die Event APIs steht da gar nichts von geschickten Daten und in anderen API Calls stehen nur Klassen wie "Refugee", welche aber nirgends näher definiert werden. Was bei API Calls mitgeschickt werden soll, und in welchem Format, muss da explizit angegeben werden. Für die geschickten Events ist das deutlich besser. Da sieht man direkt, was dort geschickt wird.

---

Und als kleiner Hinweis: In den Tests müssen nicht alle Attribute auf alle Fälle geprüft werden. Da reichen 1-2 pro API Request beispielhaft aus. Das letzte Mal hatte ich das nur angekreidet, weil es gar keine Negativfälle gab. Aber teilweise 10+ Tests nur dafür zu schreiben, ist dann doch etwas Overkill.

2022-05-03 07:18 UTC, jt128 commented
Ist noch WIP, bitte noch nicht mergen, hab gestern die eine route mit der registierung nicht mehr komplett geschafft

2022-05-07 10:05 UTC, jt128 commented
- Event zusammen in zugehörigen API Call
-  fehlende Logik in den API Calls
- Unterkunft REST API Calls (Ordner api/private/housing)
    - Test hinzugefügt
    - json Schema implementiert
- Updates des Sprint-Meetings implementiert

2022-05-07 10:08 UTC, jt128 commented
Bereit für einen zweiten Review.

2022-05-09 10:57 UTC, SgtEpic requested changes
Alles super soweit.

Wir haben ein einigen Stellen das Problem, dass wir noch nicht mit SmartAuth arbeiten können. Du musst an einigen Stellen ja überprüfen, ob der User eingeloggt ist.

Damit du nicht vergisst das später irgendwo hinzuzufügen, würde ich sagen, dass du für diesen Check eine Funktion schreibst, die das macht. 
Die würde erstmal nur ein Prototyp sein, und immer bspw. true zurückgeben. Aber wenn SmartAuth dann endlich verfügbar ist, musst du das nurnoch an dieser einen Stelle ändern, und nicht mehr überall im Code mit dem Risiko eine der vielen Stellen zu vergessen.

2022-05-12 07:01 UTC, merged